### ISSUE TITLE
Not able to enter the username

### ISSUE THREAD

**Issue by bhaveshj2611** [chinesedfan/clist-ex#11]
<img width="310" alt="{FF31795D-734C-4BC3-9793-DED710254EA3}" src="https://github.com/user-attachments/assets/7f650bc5-f266-4710-bf26-93bb3f6ff720">

Not able to enter the username, says account does not exist while I tried it with even creator's handle and still it shows that error.

**Comment by chinesedfan** [comment]
Sadly, clist changed its API, and I have sent an issue https://github.com/aropan/clist/issues/419.

Before it is fixed, you can try following steps as an workaround,
1. Find your account id by the exact user handle. i.e. (notice that leetcode handle has a strange suffix)
- https://clist.by/api/v4/account/?limit=5&resource=leetcode.com&handle=chinesedfan%40.com
- https://clist.by/api/v4/account/?limit=5&resource=codechef.com&handle=chinesedfan

2. Save by Chrome debug mode (F12) -> Application -> Local storage,
- Key is local-accounts
- Value is {"leetcode.com":{"handle":"chinesedfan@.com","id":2276684},"codechef.com":{"handle":"chinesedfan","id":3376140}}

**Comment by bhaveshj2611** [comment]
Thanks for the update, Did this and works all good :)

**Comment by chinesedfan** [comment]
clist has updated its API with handle__startswith parameter, and I have also updated my project.
