### ISSUE TITLE
Required detailed requirements/prerequisites and steps to setup

### ISSUE THREAD

**Issue by Rukmaiwad** [chinesedfan/clist-ex#2]
I want to contribute to this project but im getting below error after running it and im unable to figure it out why im getting this error.

<img width="1438" alt="image" src="https://github.com/chinesedfan/clist-ex/assets/106620566/7cf0b786-23ad-48c0-ad7a-9fffc43c492a">

Required detailed requirements/prerequisites and steps to setup

**Comment by chinesedfan** [comment]
@Rukmaiwad [New section](https://github.com/chinesedfan/clist-ex#how-to-run) about how to prepare API key was added in README. Enjoy!

**Comment by Rukmaiwad** [comment]
thanks for sharing
