### ISSUE TITLE
Display Alert to set their own API key

### ISSUE THREAD

**Issue by manas-2003** [chinesedfan/clist-ex#9]
Since the default API key supports only 10 requests per minute. A popup/alert can be displayed in the home page, that tells the users to add their own API key by clicking the settings tab.

If this is something you want to implement ??? then i can work on it !!!!

**Comment by chinesedfan** [comment]
Now there is a simple tips for first-time users,
```
It may cost more time when loading contests at the first time. If failed, please switch LeetCode/CodeChef tabs to retry.
```

How about append some words like, "Or go to Settings tab to set another API key to avoid requests rate limit"? I am not an English native speaker. Glad to receive your help. :)
